### ISSUE TITLE
edrumulus_gui.py removes trigger settings, if killed

### ISSUE THREAD

**Issue by 3hhh** [corrados/edrumulus#108]
To reproduce:

1. Start `edrumulus_gui.py`.
2. E.g. remove the Teensy controller from USB to make it hang (this may be a separate bug of its own).
3. Kill `edrumulus_gui.py`
4. Notice that the `trigger_setting.txt` is 0 bytes.

**Comment by corrados** [comment]
This is annoying. Thanks for reporting. I have just implemented a fix for this issue.

**Comment by 3hhh** [comment]
Nice, thanks!
