### ISSUE TITLE
Add video to readme

### ISSUE THREAD

**Issue by thijstriemstra** [corrados/edrumulus#124]
Is it ok to add https://www.youtube.com/watch?v=YWE1LgwQbbQ to the readme, if so, I'll open a PR for it.

**Comment by corrados** [comment]
This is what is the intention of the pinned discussion thread: https://github.com/corrados/edrumulus/discussions/28

**Comment by corrados** [comment]
I have now added a gallery page similar to what open-e-drums does on their page https://open-e-drums.com/gallery.html.

![grafik](https://github.com/corrados/edrumulus/assets/46655886/920dfe88-e072-43bd-aaf3-61e6d306d436)

https://github.com/corrados/edrumulus/blob/main/doc/gallery.md

**Comment by thijstriemstra** [comment]
thanks!
