### ISSUE TITLE
Bad cymbal rim dynamics

### ISSUE THREAD

**Issue by 3hhh** [corrados/edrumulus#133]
I noticed that the cymbal rim dynamics are generally bad - there's just one or two velocity levels even though I have rim boost set to zero.

This may be related to my experiments in https://github.com/corrados/edrumulus/discussions/126, but I doubt that as the cymbal piezo value should be taken for the MIDI velocity and not the rim switch value.

**Comment by corrados** [comment]
I cannot reproduce this issue. With my Roland CY pad, I get good dynamics when I hit the rim.

**Comment by 3hhh** [comment]
Interesting. Then I'll have to investigate this further...

**Comment by 3hhh** [comment]
So I went to some lengths to obtain proper samples from my Teensy with [this code](https://gist.github.com/3hhh/94f7199d1ebea5dd0502415375400813).
(Btw it would be useful to have some standardized way of obtaining samples in the repo.)

The results:
![crash_rim_hard](https://github.com/corrados/edrumulus/assets/13033030/12392d78-6f99-4e29-8eb0-8ec2c1b12b0b)
![crash_rim_med](https://github.com/corrados/edrumulus/assets/13033030/a5d1771c-0e80-4cfd-8de7-dca278b088f3)
![crash_rim_soft](https://github.com/corrados/edrumulus/assets/13033030/4211e916-cf4d-43e2-af12-feaa345e9ba7)
![ride_bell_hard](https://github.com/corrados/edrumulus/assets/13033030/1efea8bf-47bb-4e96-b0e7-7805d852463a)
![ride_bell_med](https://github.com/corrados/edrumulus/assets/13033030/7ae7213b-c872-48ee-8f8b-b7fc5ce7dfb2)
![ride_bell_soft](https://github.com/corrados/edrumulus/assets/13033030/48458281-d4d1-4280-952a-16eb9e708c1a)
![ride_rim_hard](https://github.com/corrados/edrumulus/assets/13033030/802ca85c-870f-45be-9bd5-c81a2cf96841)
![ride_rim_med](https://github.com/corrados/edrumulus/assets/13033030/b98bd6e9-5f84-4093-b4f0-abcfdc4ee809)
![ride_rim_soft](https://github.com/corrados/edrumulus/assets/13033030/2439a44e-3b97-4cc0-bcab-1714494a59e2)


Unfortunately I cannot see any fault in my signals as their peak voltage clearly indicates the velocity (IIRC my hard ride rim hit wasn't so hard). Also, the rim switch capacitor circuit correctly indicates that it was used - admittedly sometimes a bit earlier or later than the hit piezo.
So in total I still think that the issue must be with the edrumulus code...

Also, with regards to https://github.com/corrados/edrumulus/discussions/126 the plots look neither good for the sample counting of the rim switch open time nor for the second threshold method to discern the bell from the edge. :-(
Maybe the velocity of the hit also has to be taken into account somehow, idk. Or use the hit piezo ripple length, but I don't understand the electronic background for that atm and it makes the different rim input impedances pointless.
Maybe I'll go back to the original circuit...

[raw data download](https://github.com/corrados/edrumulus/files/13718414/all.tar.gz)

**Comment by corrados** [comment]
Maybe it is an issue with the internal pad trigger parameters. Maybe Edrumulus detects the main peak at the beginning of the burst:
![grafik](https://github.com/corrados/edrumulus/assets/46655886/35ad36a9-5132-4bc3-a968-cdb5c8822a49)
BTW, you should use logarithmic voltage-axis to better visualize the dynamics of the signal.

**Comment by 3hhh** [comment]
On 12/20/23 07:21, Volker Fischer wrote:
> Maybe it is an issue with the internal pad trigger parameters. Maybe Edrumulus detects the main peak at the beginning of the burst

Ok, I increased the scan time to 8ms and since then I obtain _some_ dynamics in the range of 70 to 127 on the MPS750x crash and ride. I still cannot obtain lower velocities though. In fact, if I move from the center of the pad to the rim at constant low velocity, I can get velocity 10-20 hits until I reach the rim - then it suddenly becomes a rim hit of velocity ~70. Any idea why?

The high scan time is only needed for rim hits - I guess I _sometimes_ (definitely not in my test above) hit the pad multiple times during a rim hit (once at the rim and possibly one more time at the regular piezo location - at least that way I appear to get better dynamics) and I guess those signals may come in at different points in time.

I haven't tested increasing the scan time with the Lemon hihat yet (it has the same issue).

**Comment by 3hhh** [comment]
I went back to the original voltage divider circuit with my parameters and I now have good cymbal rim dynamics for the MPS750x pads again. So apparently this issue was a byproduct of [my capacitor circuit for the rim switch](https://github.com/corrados/edrumulus/discussions/126).

The Lemon hihat is still not perfect imo, but I'll look into that separately. Maybe the parameters could be chosen a bit differently.
