### ISSUE TITLE
Direct piezo hits sometimes cause a MIDI mute

### ISSUE THREAD

**Issue by 3hhh** [corrados/edrumulus#142]
As discussed in https://github.com/corrados/edrumulus/discussions/139#discussioncomment-9177871 direct very hard piezo hits on my MPS750x sometimes cause no edrumulus MIDI output.

In fact, there appears to be a very low volume (velocity usually around 1) MIDI note instead. This note and others were correctly filtered out as cross-talk by my `xtalk` script, which is why I had incorrectly not seen and mentioned them before.

After some investigation I came to the conclusion that the missing MIDI output is likely caused by the edrumulus clipping compensation algorithm:

By commenting in [these lines](https://github.com/corrados/edrumulus/blob/498634ce4e4da4f97486fd742cf2bd6d79b343ff/edrumulus.cpp#L1007-L1021) I obtained the following output whenever I ran into the bug:
```
1.
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 0.00 0.00 0.00 0.00 0.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00

34 76 34 76 34

1303.47 1139.37 13 1221.42 -463.04 0.00

2.
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 0.00 0.00 0.00 2.00 0.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 

34 76 34 76 34

191.25 909.14 14 550.19 -1134.04 0.00 

3.
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 0.00 0.00 0.00 0.00 0.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 2.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00

34 76 34 76 34

155.27 341.17 14 248.22 -1436.04 0.00
```

Please note that the peak (last value) is always considered to be zero by edrumulus whenever I ran into the bug.

Three samples where it works correctly:
```
1.
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 1.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 0.00 0.00 0.00 2.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00

38 76 38 76 38

1509.29 1125.25 5 1317.27 -70.61 0.00 1.45 2434.53

2.
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 1.00 0.00 0.00 1.00 1.00 1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 

37 76 37 76 37

925.41 1537.37 5 1231.39 -156.59 0.00 1.45 2434.70

3.
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 1.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 1.00 0.00 0.00 2.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 2.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00

37 76 37 76 37

257.99 1290.95 5 774.47 -613.99 0.00 1.45 2435.54
```

**Comment by corrados** [comment]
Great that you found the cause of the issue and thank you for the detailed debug data.

> In fact, there appears to be a very low volume (velocity usually around 1) MIDI note instead. This note and others were correctly filtered out as cross-talk by my xtalk script, which is why I had incorrectly not seen and mentioned them before.

Yea, that makes totally sense now.

**Comment by corrados** [comment]
That is very interesting. I just tried it out to dump the debug data on my PD-80R where the clipping compensation works just fine, and I got the following numbers:

```
19:47:37.999 -> 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 1.00 1.00 1.00 
19:47:38.032 -> 27 30 27 30 27
19:47:38.032 -> 1378.04 0.00 3 1378.04 -455.95 0.00 nan nan
```
The nan are obviously wrong and a bug. What puzzles me is that I see nan and in your case there are just 6 values given where I expect 8 values. I assume that you also have nan values but your serial plotter may just omit the nan values.

**Comment by corrados** [comment]
I guess you do not get the nan because I am using ESP32 and your are a Teensy. These two devices most probably treat nan values differently.

Anyway, I think I found the issue but have not a solution how to solve it. After deriving the clipping compensation in Octave, I later introduced a limit in the C++ implementation which was not there in the Octave reference code:

https://github.com/corrados/edrumulus/blob/89ccdd25d220467a12051861267e0b5f686c632e/edrumulus.cpp#L588

The "min ( 5," seems to cause the issue. If you like, you could remove that limit and try again if you still get the muted MIDI signals. Anyway, the limit was introduced by a reason and now I have to find a solution which still applies a limit but does not produce the nan values...

**Comment by corrados** [comment]
I have just applied a fix to Git main branch. Can you please test if this fixes your issue?

**Comment by 3hhh** [comment]
Yes, that fixes it. Many thanks!
Maybe that'll make me look into pos sensing for the MPS750x again...

Btw you might be interested [in my latest project](https://github.com/3hhh/klickly).
