### ISSUE TITLE
drumgizmo edrumulus branch doesn't compile on ubuntu 24.04

### ISSUE THREAD

**Issue by 3hhh** [corrados/edrumulus#156]
It doesn't compile anymore on ubuntu 24.04 as some header was renamed.

Required patch:
```
diff --git a/plugin.h b/plugin.h
index 4c22943..7bf19f2 100644
--- a/plugin.h
+++ b/plugin.h
@@ -29,7 +29,7 @@
 #include <vector>
 #include <string>

-#include <cstdlib>
+#include <cstdint>


 #if defined(WIN32)
```

EDIT: Updated as apparently this wasn't fixed in drumgizmo upstream yet.

**Comment by corrados** [comment]
Thanks for reporting. I just upgraded my Ubuntu to the newest version and will try it out on my PC.

**Comment by corrados** [comment]
I just saw that Bent had already fixed this issue: http://git.drumgizmo.org/plugingizmo.git/commit/?id=a88c76afd8fbfe31b76010bac34c1437b1927245

**Comment by corrados** [comment]
I have just updated the edrumulus branch to use that fix: http://git.drumgizmo.org/drumgizmo.git/commit/?h=edrumulus

**Comment by corrados** [comment]
Note: Since this fix is in a sub-module, you need to do a git submodule update.
