### ISSUE TITLE
BOARD_LED_PIN definition

### ISSUE THREAD

**Issue by thijstriemstra** [corrados/edrumulus#33]
Currently `BOARD_LED_PIN` is defined in edrumulus_hardware.h. Since my ESP32 doesn't have a builtin LED, [I need to change it to a different GPIO nr](https://github.com/corrados/edrumulus/compare/thijstriemstra_prototype). Ideally I wouldn't want to touch anything in edrumulus source except for the .ino file so my request is to move or add support for defining the BOARD_LED_PIN in the .ino instead, leaving edrumulus source untouched.

**Comment by corrados** [comment]
The BOARD_LED_PIN definition is specific to a developer board. E.g., for the ESP32 board I own, it is pin 2 and this should not be changed. That is the reason why it is defined in the edrumulus_hardware header file. You, as an end user, should not change it.

But the current edrumulus code does already support your request in my opinion. The variable which is actually used for the board LED pin is "status_LED_pin" and this is defined in edrumulus.ino file:
https://github.com/corrados/edrumulus/blob/d7a8f19a484a9471233c446e7a2fbfa6572bf7d5/edrumulus.ino#L40

So, you could simply write:
`const int status_LED_pin    = 23;//BOARD_LED_PIN; // internal LED used for overload indicator`
and therefore need no changes in edrumulus_hardware.h.

**Comment by thijstriemstra** [comment]
Thanks!
