### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by thijstriemstra** [corrados/edrumulus#40]
It would be useful for people using edrumulus in their project to be able to display/determine a version for Edrumulus. For my first prototype, if I add a display, this would be the first thing I want to see when the device is on.

**Comment by corrados** [comment]
This is now supported:
![grafik](https://user-images.githubusercontent.com/46655886/148799483-4f609fe3-4f13-468e-9796-248beacc2bc8.png)

**Comment by thijstriemstra** [comment]
thanks @corrados Only I was more thinking of adding it to `edrumulus.h` which my customized version of `edrumulus.ino` loads. I would expect any user of edrumulus to copy the .ino, make their own adjustments, and include the external edrumulus library (which has the version nr). Your approach would be something the end user uses for their own version nr, e.g. `MyEdrums 0.1`.

**Comment by thijstriemstra** [comment]
thanks. can you also use the version number in the changelog (and bump it up when a new changelog entry is added)? And creating a git tag after that would be great.

**Comment by corrados** [comment]
Sure. It's done now.
