### ISSUE TITLE
edrumuluscontrol.m: add midi in/out labels

### ISSUE THREAD

**Issue by thijstriemstra** [corrados/edrumulus#44]
When I run the edrumuluscontrol I always have to check the code what table is midi in, and which one is midi out. Would be very useful (also to new users) to have these tables labeled like you did with 'Edrumulus settings'. I tried looking into adding it myself but this programming language (matlab?) is very foreign to me.

![octave-menu](https://user-images.githubusercontent.com/305679/149175047-7e26772b-a25c-48ce-8d17-fa1e7aef5495.jpg)

**Comment by corrados** [comment]
It's done:
![grafik](https://user-images.githubusercontent.com/46655886/150640127-27e0f9ea-01b7-406b-bb14-12990e0381b8.png)

Implementation commit: https://github.com/corrados/edrumulus/commit/e1ffaeb04c80c755f7c01564fd773d02fbb1f703

**Comment by thijstriemstra** [comment]
awesome, thanks!
